-- Take note of CASCADE.
DROP TABLE Passwords CASCADE;
DROP TABLE InvolvedIn CASCADE;
DROP TABLE Cases CASCADE;
DROP TABLE Agents CASCADE;
DROP TABLE People CASCADE;
DROP TABLE Locations CASCADE;
DROP TABLE Genders CASCADE;
DROP TABLE Professions CASCADE;